name: erantech
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  flutter_svg: ^2.0.9
  expansion_tile_card: ^3.0.0
  flutter_riverpod: ^2.4.10
  equatable: ^2.0.5
  go_router: ^13.1.0
  jwt_decoder: ^2.0.1
  dio: ^5.4.0
  fl_chart: ^0.66.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.8

  flutter_lints: ^2.0.0

flutter_native_splash:
  image: assets/images/splash_logo.png
  color: "#A84747"
  icon_background_color: "#A84747"
  android_gravity: fill_horizontal

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/splash_logo.png
    - assets/images/bg_image.jpg
    - assets/images/menu_svg/accounting.svg
    - assets/images/menu_svg/export.svg
    - assets/images/menu_svg/finance.svg
    - assets/images/menu_svg/logistic.svg
    - assets/images/menu_svg/management.svg
    - assets/images/menu_svg/purchasing.svg
    - assets/images/menu_svg/user_male.png
    - assets/images/menu_svg/user_female.png
    - assets/images/menu_svg/salesman.svg
    - lib/src/helpers/
  #   - images/a_dot_ham.jpeg



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

